Make handlers
openprocurement/openprocurement.bridge.contracting pull request #49
Opened 2018-10-12 14:35 UTC by tarasvaskiv

2018-10-18 11:08 UTC, VDigitall requested changes

2018-10-18 11:08 UTC, VDigitall commented on buildout.cfg
> +    ExtendedJournalHandler
Додати залежність на `bridge.basic`

2018-10-18 11:08 UTC, VDigitall commented on openprocurement/bridge/contracting/tests/base.py
> +class AdaptiveCache(object):
Імпортувати з `bridge.basic`

2018-10-18 11:08 UTC, VDigitall commented on templates/contracting_data_bridge.yaml
> +    filters:
Написати вираз який би викидав тендери з `procurementMethodType = [  'competitiveDialogueUA', 'competitiveDialogueEU']`

2018-10-18 12:22 UTC, tarasvaskiv commented on buildout.cfg
> +    ExtendedJournalHandler
Виправив, додав додатковим комітом, тут чомусь не видно https://github.com/openprocurement/openprocurement.bridge.contracting/pull/49/commits/78d8b9c76699b107f06b38d623d46145c5bb4ec9

2018-10-19 05:31 UTC, VDigitall approved these changes

2018-10-19 05:33 UTC, merged